version: '3.8'

services:
  kernel-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpi4-kernel-builder
    volumes:
      - .:/kernel-build/host
      - kernel-output:/kernel-build/output
      - kernel-source:/kernel-build/linux-6.12
    working_dir: /kernel-build
    environment:
      - ARCH=arm64
      - CROSS_COMPILE=aarch64-linux-gnu-
      - KERNEL=kernel8
    tty: true
    stdin_open: true

volumes:
  kernel-output:
    driver: local
  kernel-source:
    driver: local